### ISSUE TITLE
Front : Imágenes Home

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#2]
En las imágenes de portada solo aparecen la alberca de adultos y la fogata, falta la alberca central y la otra foto tipo lifestyle.

**Link:** http://hacienda1800.com/test/index.php

**Fotos:** https://drive.google.com/open?id=1wqVRdMSE7Z_wevPjEN7ZQfq4tp3-v2RJ

![Captura de pantalla 2019-10-11 a la(s) 10.33.55.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/e573dcf3-5cba-4896-9b50-2fa70582190f)

**Comment by gamanox** [comment]
ya se puede usar los controles del 360

**Comment by KassWTF** [comment]
Revisar si ya existe un ícono para mostrar que son 360

**Comment by KassWTF** [comment]
No me sale el icon
