### ISSUE TITLE
Front : Menu-Home

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#21]
El botón de Home te lleva a la página final de 1800: http://hacienda1800.com/index.php

**Link:** http://hacienda1800.com/test/index.php?#

![Captura de pantalla 2019-10-11 a la(s) 11.23.48.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/947cc52d-dfcb-406b-9c1a-694bfea0e463)

**Comment by gamanox** [comment]
@srlechuga18 igual es el base url `{$base_dir}`
