### ISSUE TITLE
Front : Espacios

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#24]
No se muestra el contenido.

**Link:** http://hacienda1800.com/index.php?controller=features

![Captura de pantalla 2019-10-11 a la(s) 11.27.11.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/507e415c-1233-441f-ad1f-02c8ec3da7a2)

**Comment by gamanox** [comment]
se corrige una vez que esté en el dominio original

**Comment by gamanox** [comment]
@srlechuga18 le puedes agregar en el HREF del link `{$base_dir}` para que apunte a la url base independientemente de la carpeta donde viva el sitio, por favor
