### ISSUE TITLE
Front : Menu-IniciarSesión

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#28]
¿Esta parte se va a quedar?

**Link:** http://hacienda1800.com/test/index.php

![Captura de pantalla 2019-10-11 a la(s) 12.02.47.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/f6c704e2-57b6-4d9b-93c4-ec20f1af278e)

**Comment by gamanox** [comment]
no es necesario

**Comment by gamanox** [comment]
@srlechuga18 puedes ocultar el elemento del menú por favor?

**Comment by srlechuga18** [comment]
Smn
