### ISSUE TITLE
Mailing

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#43]
Al registrarse aparece el logo de Qlo, ¿podemos hacer que salga el de 1800?

![Captura de pantalla 2019-10-11 a la(s) 12.42.25.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/d36e896a-e0de-4fc8-afb8-8310810cef87)

**Comment by gamanox** [comment]
@KassWTF me pasas el logo que llevaría? en png por favor
