### ISSUE TITLE
Backoffice : Precios

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#63]
Los precios con descuentos de las habitaciones no coinciden con los que están en el front.

![Captura de pantalla 2019-10-14 a la(s) 14.40.19.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/060e2fdb-f5fa-4d2a-b9df-da35e8d50611)

**Comment by gamanox** [comment]
@KassWTF podemos revisar éste bug juntos para entender bien qué se necesita?
