### ISSUE TITLE
Backoffice : Traducciones

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#65]
Aún no me deja añadir las traducciones.

**Comment by KassWTF** [comment]
**Traducciones que me deja editar:**
- Front Office
- Nombres de los campos
- PDF

**Traducciones con restricción de campos [permitidos](http://hacienda1800.com/test/backoffice/index.php?controller=AdminTranslations&lang=es&type=back&token=047bd035816f618f56d7677e704682ca):**
- Back Office

**Traducciones que _NO_ me deja editar:**
- Mensajes de error
- Módulos instalados
- Plantillas de e-mail

**Comment by KassWTF** [comment]
Borré caché y aún no me deja.

**Comment by gamanox** [comment]
éstas traducciones las vamos a hacer a mano nosotros
