### ISSUE TITLE
Front : Espacios

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#80]
No se ven las imágenes ni la información.

Actual: ![Captura de pantalla 2019-10-16 a la(s) 12.11.42.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/c4b4e694-bca5-48dd-9a24-a8cf451e1f92)

Diseño: ![Captura de pantalla 2019-10-16 a la(s) 12.13.52.png](https://images.zenhubusercontent.com/5d6fe1b5e370a20001310cd3/2db9215e-e473-4100-9a4b-3916988c3c48)

**Comment by KassWTF** [comment]
Falta el botón de **Reservar** en el restaurante. Por ahora diijimos que también te lleve al whats del hotel.

En **Desktop** centrar el texto en la caja gris para no tener tanto espacio vacío

**Comment by KassWTF** [comment]
Falta el botón de Reservar en el restaurante.

**Comment by gamanox** [comment]
agregar campo de reserva para el restaurante en la base de datos

**Comment by gamanox** [comment]
link a whatsaaa
