### ISSUE TITLE
Front : Menú Desktop - Contacto

### ISSUE THREAD

**Issue by KassWTF** [we-the-force/h1800-ws#87]
Agregar un sexto ícono al centro en donde al dar clic te lleve a la sección de contacto.

Diseño: https://www.figma.com/file/P7iG74sxquy2N5MBOLLtfE/Hacienda-1800?node-id=5268%3A202

Español: CONTACTO
Inglés: CONTACT

**Comment by gamanox** [comment]
@KassWTF a dónde va a dirigir el botón de contacto?
